# Generated by Django 6.0.6 on 2026-06-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_students_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
